name: ghcr-marimo
on:
  push:
    branches: [ "main" ]

jobs:
  build-amd64:
    runs-on: ubuntu-latest
    if: github.repository == 'stfc/alc-dls-exafs'
    permissions:
      packages: write
      contents: read
    steps:
      - name: 'clone the repo'
        uses: actions/checkout@v4
      - name: 'login to ghcr'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name:
        run: |
          mkdir ./containers/assets/
          cp -r notebooks ./containers/assets/
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./containers
          file: ./containers/Dockerfile.marimo
          push: true
          tags: |
            ghcr.io/stfc/alc-dls-exafs/marimo:amd64-${{ github.sha }}
            ghcr.io/stfc/alc-dls-exafs/marimo:amd64-latest
  build-arm64:
    runs-on: ubuntu-24.04-arm
    if: github.repository == 'stfc/alc-dls-exafs'
    permissions:
      packages: write
      contents: read
    steps:
      - name: 'clone the repo'
        uses: actions/checkout@v4
      - name: 'login to ghcr'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: assets
        run: |
          mkdir ./containers/assets/
          cp -r notebooks ./containers/assets/

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./containers
          file: ./containers/Dockerfile.marimo
          push: true
          tags: |
            ghcr.io/stfc/alc-dls-exafs/marimo:arm64-${{ github.sha }}
            ghcr.io/stfc/alc-dls-exafs/marimo:arm64-latest
